export const LOCALSTORAGE_CHECKIN_KEY = 'LOCALSTORAGE_CHECKIN_KEY';
export const LOCALSTORAGE_LOG_KEY = 'LOCALSTORAGE_LOG_KEY';
export const LOCALSTORAGE_POOLS_KEY = 'LOCALSTORAGE_POOLS_KEY';
export const LOCALSTORAGE_ENTRIES_KEY = 'LOCALSTORAGE_ENTRIES_KEY';
export const LOCALSTORAGE_RUNNING_KEY = 'LOCALSTORAGE_RUNNING_KEY';
export const ERROR_UNINITIALIZED_CONTEXT = 'Error: Uninitialized context';
