 export const LOCALSTORAGE_CHECKIN_KEY = 'LOCALSTORAGE_CHECKIN_KEY';
export const LOCALSTORAGE_LOG_KEY = 'LOCALSTORAGE_LOG_KEY';
export const ERROR_UNINITIALIZED_CONTEXT = 'Error: Uninitialized context';
